name: WorkflowTests

on: 
  push:
    branches:
      - main

jobs:
  tareas:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4

      - name: Bajar pytest
        run: pip install pytest

      - name: Probar codigo
        run: python3 -m pytest test.py


